package gov.tak.platform.symbology.milstd2525;

import armyc2.c2sd.renderer.utilities.SymbolDef;
import gov.tak.api.symbology.ISymbolTable;
import gov.tak.api.symbology.ShapeType;

interface MilStd2525cDrawRuleConstants
{
    int DRAW_CATEGORY_LINE = SymbolDef.DRAW_CATEGORY_LINE;
    int DRAW_CATEGORY_ARROW = SymbolDef.DRAW_CATEGORY_ARROW;
    int DRAW_CATEGORY_ROUTE = SymbolDef.DRAW_CATEGORY_ROUTE;
    int DRAW_CATEGORY_POLYGON = SymbolDef.DRAW_CATEGORY_POLYGON;
    int DRAW_CATEGORY_SUPERAUTOSHAPE = SymbolDef.DRAW_CATEGORY_SUPERAUTOSHAPE;
    int DRAW_CATEGORY_TWOPOINTARROW = SymbolDef.DRAW_CATEGORY_TWOPOINTARROW;
    int DRAW_CATEGORY_TWOPOINTLINE = SymbolDef.DRAW_CATEGORY_TWOPOINTLINE;
    int DRAW_CATEGORY_RECTANGULAR_PARAMETERED_AUTOSHAPE = SymbolDef.DRAW_CATEGORY_RECTANGULAR_PARAMETERED_AUTOSHAPE;
    int DRAW_CATEGORY_AUTOSHAPE = SymbolDef.DRAW_CATEGORY_AUTOSHAPE;
    int DRAW_CATEGORY_SECTOR_PARAMETERED_AUTOSHAPE = SymbolDef.DRAW_CATEGORY_SECTOR_PARAMETERED_AUTOSHAPE;
    int DRAW_CATEGORY_3D_AIRSPACE = SymbolDef.DRAW_CATEGORY_3D_AIRSPACE;
    int DRAW_CATEGORY_TWO_POINT_RECT_PARAMETERED_AUTOSHAPE = SymbolDef.DRAW_CATEGORY_TWO_POINT_RECT_PARAMETERED_AUTOSHAPE;
    int DRAW_CATEGORY_POINT = SymbolDef.DRAW_CATEGORY_POINT;
    int DRAW_CATEGORY_CIRCULAR_PARAMETERED_AUTOSHAPE = SymbolDef.DRAW_CATEGORY_CIRCULAR_PARAMETERED_AUTOSHAPE;
    int DRAW_CATEGORY_CIRCULAR_RANGEFAN_AUTOSHAPE = SymbolDef.DRAW_CATEGORY_CIRCULAR_RANGEFAN_AUTOSHAPE;
    int DRAW_CATEGORY_DONOTDRAW = SymbolDef.DRAW_CATEGORY_DONOTDRAW;
    int DRAW_CATEGORY_UNKNOWN = SymbolDef.DRAW_CATEGORY_UNKNOWN;
}
